version: '3'
volumes:
  mc-data:
services:
  minecraft:
    image: itzg/minecraft-server
    env_file: ./minecraft/minecraft.env
    depends_on:
      - http
    ports:
      - 25565:25565
    volumes:
      - mc-data:/data
      - ./minecraft:/resources:ro      
  http:
    image: octosystems/octocraft-nginx
    build: ./nginx
    ports:
      - 80:80    